add - handling sector entered and sector quit events
f1xmAn/stateful-functions-app-sample pull request #1
Opened 2021-02-10 10:07 UTC by Csipon

2021-02-10 19:57 UTC, f1xmAn requested changes

2021-02-10 19:57 UTC, f1xmAn commented on src/main/java/com/github/f1xmAn/statefun/crossedpathsdetector/FnSector.java
> +    private final PersistedTable<String, SectorEnteredEvent> personsInSector
Why do you keep SectorEnteredEvent? Seems PersistedAppendingBuffer fits better for the case

2021-02-17 17:10 UTC, Csipon commented on src/main/java/com/github/f1xmAn/statefun/crossedpathsdetector/FnSector.java
> +    private final PersistedTable<String, SectorEnteredEvent> personsInSector
if we use PersistedAppendingBuffer instead of PersistedTable then removing a Person from the Sector will be always via the iterator

2021-02-28 09:43 UTC, f1xmAn commented on src/main/java/com/github/f1xmAn/statefun/crossedpathsdetector/FnSector.java
> +        if (!personsInSector.get().isEmpty()) {
Remove explicit condition

2021-03-06 12:06 UTC, f1xmAn commented on src/main/java/com/github/f1xmAn/statefun/crossedpathsdetector/FnSector.java
> +            personsInSector.get().forEach(pId -> sendPathsCrossedEvent(context, pId, event));
It would be a clearer code if you map to PathsCrossedEvent here instead of a method "sendPathsCrossedEvent" receiving SectorEnteredEvent

2021-03-06 12:11 UTC, f1xmAn commented on src/main/java/com/github/f1xmAn/statefun/crossedpathsdetector/FnSector.java
> +    private void onSectorEnteredEvent(Context context, SectorEnteredEvent event) {
Will entered person receive an event with all people in the sector?

2021-03-06 12:20 UTC, f1xmAn commented on src/test/java/com/github/f1xmAn/statefun/crossedpathsdetector/FnSectorTest.java
> +        verify(context, times(2)).send(eq(FnPerson.TYPE), anyString(), any(PathsCrossedEvent.class));
prepare exact events and verify against them. This line verifies just the number of times any PathsCrossedEvent sent

2021-03-06 12:21 UTC, f1xmAn commented on src/test/java/com/github/f1xmAn/statefun/crossedpathsdetector/FnSectorTest.java
> +        verify(personsInSector).remove(alicePersonQuitBlueSector().getPersonId());
No reason for mock here, verify exact value

2021-03-06 12:22 UTC, f1xmAn commented on src/test/java/com/github/f1xmAn/statefun/crossedpathsdetector/FnSectorTest.java
> +        verify(context, times(0)).send(eq(FnPerson.TYPE), anyString(), any(PathsCrossedEvent.class));
Would it be better if you verify that context wasn't invoked at all?

2021-03-06 12:22 UTC, f1xmAn commented on src/test/java/com/github/f1xmAn/statefun/crossedpathsdetector/FnSectorTest.java
> +    private Set<String> personsInSector;
Mock behaviour, not data.

2021-03-08 16:52 UTC, merged